{
 "title": "PI2",
 "time": { "from": "2022-01-14T12:21:00.517Z", "to": "2022-01-16T02:38:09.960Z" },
 "panels": [
  { "title": "Temperature", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "All sensors",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1\" or r[\"_measurement\"] == \"2\" or r[\"_measurement\"] == \"3\" or r[\"_measurement\"] == \"4\" or r[\"_measurement\"] == \"10\" or r[\"_measurement\"] == \"11\" or r[\"_measurement\"] == \"12\" or r[\"_measurement\"] == \"13\" or r[\"_measurement\"] == \"14\" or r[\"_measurement\"] == \"15\" or r[\"_measurement\"] == \"16\" or r[\"_measurement\"] == \"17\" or r[\"_measurement\"] == \"5\" or r[\"_measurement\"] == \"6\" or r[\"_measurement\"] == \"7\" or r[\"_measurement\"] == \"8\" or r[\"_measurement\"] == \"9\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Current temperature of all sensors",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"1\" or r[\"_measurement\"] == \"2\" or r[\"_measurement\"] == \"3\" or r[\"_measurement\"] == \"4\" or r[\"_measurement\"] == \"10\" or r[\"_measurement\"] == \"11\" or r[\"_measurement\"] == \"12\" or r[\"_measurement\"] == \"13\" or r[\"_measurement\"] == \"14\" or r[\"_measurement\"] == \"15\" or r[\"_measurement\"] == \"16\" or r[\"_measurement\"] == \"17\" or r[\"_measurement\"] == \"5\" or r[\"_measurement\"] == \"6\" or r[\"_measurement\"] == \"7\" or r[\"_measurement\"] == \"8\" or r[\"_measurement\"] == \"9\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Temperature sensors on desks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"5\" or r[\"_measurement\"] == \"10\" or r[\"_measurement\"] == \"14\" or r[\"_measurement\"] == \"11\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"5\" or r[\"_measurement\"] == \"10\" or r[\"_measurement\"] == \"14\" or r[\"_measurement\"] == \"11\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Door wall temperature",
   "type": "timeseries",
   "description": "Evolution of the temperature of the sensors located on the door wall",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"6\" or r[\"_measurement\"] == \"7\" or r[\"_measurement\"] == \"8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n    |> filter(fn : (r) => r[\"location\"] ==\"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"6\" or r[\"_measurement\"] == \"7\" or r[\"_measurement\"] == \"8\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n    |> filter(fn : (r) => r[\"location\"] ==\"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Right and left walls temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>r[\"_measurement\"] == \"1\" or r[\"_measurement\"] == \"2\" or r[\"_measurement\"] == \"3\" or r[\"_measurement\"] == \"4\" )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn : (r) => r[\"location\"] ==\"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>r[\"_measurement\"] == \"1\" or r[\"_measurement\"] == \"2\" or r[\"_measurement\"] == \"3\" or r[\"_measurement\"] == \"4\" )\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn : (r) => r[\"location\"] ==\"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Window wall , stuck to the wall",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"13\" or r[\"_measurement\"] == \"9\" or r[\"_measurement\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"13\" or r[\"_measurement\"] == \"9\" or r[\"_measurement\"] == \"12\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "window temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"15\"  or r[\"_measurement\"] == \"17\" or r[\"_measurement\"] == \"16\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"15\"  or r[\"_measurement\"] == \"17\" or r[\"_measurement\"] == \"16\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Minimum temperature registered",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"15\" or r[\"_measurement\"] == \"14\" or r[\"_measurement\"] == \"13\" or r[\"_measurement\"] == \"11\" or r[\"_measurement\"] == \"12\" or r[\"_measurement\"] == \"10\" or r[\"_measurement\"] == \"1\" or r[\"_measurement\"] == \"16\" or r[\"_measurement\"] == \"17\" or r[\"_measurement\"] == \"2\" or r[\"_measurement\"] == \"3\" or r[\"_measurement\"] == \"4\" or r[\"_measurement\"] == \"5\" or r[\"_measurement\"] == \"6\" or r[\"_measurement\"] == \"8\" or r[\"_measurement\"] == \"7\" or r[\"_measurement\"] == \"9\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Maximum temperature registered",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"merakiBucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"15\" or r[\"_measurement\"] == \"14\" or r[\"_measurement\"] == \"13\" or r[\"_measurement\"] == \"11\" or r[\"_measurement\"] == \"12\" or r[\"_measurement\"] == \"10\" or r[\"_measurement\"] == \"1\" or r[\"_measurement\"] == \"16\" or r[\"_measurement\"] == \"17\" or r[\"_measurement\"] == \"2\" or r[\"_measurement\"] == \"3\" or r[\"_measurement\"] == \"4\" or r[\"_measurement\"] == \"5\" or r[\"_measurement\"] == \"6\" or r[\"_measurement\"] == \"8\" or r[\"_measurement\"] == \"7\" or r[\"_measurement\"] == \"9\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"L404\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}